-- Consent-aware anonymous storefront funnel. Applied to Supabase on 2026-09-18.
create table if not exists public.storefront_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('page_view','view_item','add_to_cart','begin_checkout')),
  session_id uuid not null,
  page_path text not null default '/',
  channel text not null default 'physical' check (channel in ('physical','ebook','site')),
  value numeric(12,2) not null default 0 check (value >= 0 and value <= 1000000),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.storefront_events enable row level security;
revoke all on table public.storefront_events from anon, authenticated;
revoke all on sequence public.storefront_events_id_seq from anon, authenticated;
grant all on table public.storefront_events to service_role;
grant usage, select on sequence public.storefront_events_id_seq to service_role;
create index if not exists storefront_events_created_idx on public.storefront_events(created_at desc);
create index if not exists storefront_events_funnel_idx on public.storefront_events(event_name, created_at desc);
create index if not exists storefront_events_session_idx on public.storefront_events(session_id, created_at desc);
comment on table public.storefront_events is 'Consent-aware anonymous ecommerce funnel events; no contact or payment data.';
